### ISSUE TITLE
Argentina should accept old format of 4 numerical digits

### ISSUE THREAD

**Issue by sullivanpt** [hacdias/zipcodes-regex#2]
Wikipedia states "[...] the CPA is still not in wide use by private persons, and even government sources and private businesses often list the base code as in the old system [...]" https://en.wikipedia.org/wiki/Postal_codes_in_Argentina

To accommodate this could you change the RegEx to also accept 4 numerical digits, something like:

```
 "AR": "^([A-Z]\\d{4}[A-Z]{3})|([A-Z]?\\d{4})$",
```

Much appreciated, and thank you for building this!

**Comment by hacdias** [comment]
Hey @sullivanpt,

I've updated it to your suggestion. Thanks for it! Please update to the newest version of the package (1.0.1) to check if everything works fine 😄

**Comment by sullivanpt** [comment]
Looks good thanks
